# Generated by Django 4.0.4 on 2022-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0003_manualcorrection_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='join_strings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
