# Generated by Django 4.0.4 on 2022-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0004_zooniversesubject_join_strings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='join_strings',
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='join_candidates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
