# Generated by Django 4.0.1 on 2022-01-31 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0005_reducedresponse_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooniverseResponseRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('workflow_id', models.IntegerField(null=True)),
                ('workflow_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('workflow_version', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('gold_standard', models.BooleanField(null=True)),
                ('expert', models.BooleanField(null=True)),
                ('metadata', models.JSONField()),
                ('annotations', models.JSONField()),
                ('subject_data', models.JSONField()),
                ('subject_ids', models.IntegerField(db_index=True)),
                ('subject_data_flat', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('zoon_name', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('workflow_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True)),
                ('bool_covenant', models.BooleanField(null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.zoon.zooniverseworkflow')),
            ],
        ),
    ]
