# Generated by Django 4.0.4 on 2022-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0006_alter_zooniversesubject_join_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='city_final',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='join_candidates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='street_address_final',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Street address'),
        ),
    ]
