# Generated by Django 4.0.4 on 2022-04-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0007_alter_zooniversesubject_city_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='street_address_final',
            field=models.TextField(blank=True, null=True, verbose_name='Street address'),
        ),
    ]
