# Generated by Django 4.0.1 on 2022-02-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0007_zooniversesubject_addition_zooniversesubject_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='bool_outlier',
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='addition_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='block_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_covenant_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='buyer_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='covenant_text_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date_day_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date_month_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date_overall_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date_year_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='lot_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='seller_score',
            field=models.FloatField(null=True),
        ),
    ]
