# Generated by Django 4.0.4 on 2022-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0008_alter_zooniversesubject_street_address_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
