# Generated by Django 4.0.4 on 2022-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0009_alter_zooniverseresponseraw_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcorrection',
            name='match_type',
            field=models.CharField(blank=True, choices=[('SL', 'Simple lot'), ('ML', 'Multiple single lots'), ('PL', 'Partial lot'), ('PD', 'Long phys description'), ('C', 'Cemetery plot'), ('PC', 'Petition covenant'), ('SE', 'Something else'), ('NG', 'No geographic information')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='match_type_final',
            field=models.CharField(blank=True, choices=[('SL', 'Simple lot'), ('ML', 'Multiple single lots'), ('PL', 'Partial lot'), ('PD', 'Long phys description'), ('C', 'Cemetery plot'), ('PC', 'Petition covenant'), ('SE', 'Something else'), ('NG', 'No geographic information')], max_length=4, null=True),
        ),
    ]
