# Generated by Django 4.0.4 on 2022-05-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0012_zooniversesubject_parcel_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraparcelcandidate',
            name='epc_type',
            field=models.CharField(blank=True, choices=[('el', 'Extra deed lot (old)'), ('me', 'Modern equivalent lot')], max_length=2, null=True),
        ),
    ]
