# Generated by Django 4.0.6 on 2022-07-28 14:29

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0013_extraparcelcandidate_epc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCovenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_confirmed', models.BooleanField(default=False)),
                ('covenant_text', models.TextField(blank=True)),
                ('addition', models.CharField(blank=True, max_length=500)),
                ('lot', models.TextField(blank=True)),
                ('block', models.CharField(blank=True, max_length=500)),
                ('seller', models.CharField(blank=True, max_length=100)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.DateField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True, verbose_name='Street address')),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='City')),
                ('cov_type', models.CharField(blank=True, choices=[('PS', 'Public submission (single property)'), ('PL', 'Plat covenant'), ('SE', 'Something else')], max_length=4, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='ManualSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('Dd', 'Deed'), ('Ot', 'Other')], max_length=4)),
                ('doc_upload', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='supporting_docs/')),
                ('comments', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('manual_covenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoon.manualcovenant')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
