# Generated by Django 4.0.6 on 2022-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0010_geojsonexport'),
        ('zoon', '0014_manualcovenant_manualsupportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcovenant',
            name='bool_parcel_match',
            field=models.BooleanField(default=False, verbose_name='Parcel match?'),
        ),
        migrations.AddField(
            model_name='manualcovenant',
            name='parcel_matches',
            field=models.ManyToManyField(to='parcel.parcel'),
        ),
    ]
