# Generated by Django 4.0.6 on 2022-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0015_manualcovenant_bool_parcel_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualcovenant',
            name='street_address',
        ),
        migrations.AddField(
            model_name='manualcovenant',
            name='join_candidates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
