# Generated by Django 4.1.2 on 2022-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0017_manualcovenant_doc_num_alter_manualcovenant_cov_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcorrection',
            name='bool_handwritten',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='bool_handwritten',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='match_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_handwritten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_handwritten_final',
            field=models.BooleanField(default=False, verbose_name='Handwritten?'),
        ),
    ]
