# Generated by Django 4.1.2 on 2022-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0018_manualcorrection_bool_handwritten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='deedpage_doc_num',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deedpage_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deedpage_s3_lookup',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
