# Generated by Django 4.1.2 on 2022-11-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0019_zooniversesubject_deedpage_doc_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_handwritten_score',
            field=models.FloatField(null=True),
        ),
    ]
