# Generated by Django 4.0.3 on 2022-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0019_zooniversesubject_median_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='image_id',
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='image_id_1',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='image_id_2',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='image_id_3',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
