# Generated by Django 4.1.2 on 2022-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0020_zooniversesubject_bool_handwritten_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='bool_handwritten_final',
            field=models.BooleanField(null=True, verbose_name='Handwritten?'),
        ),
    ]
