# Generated by Django 4.1.2 on 2022-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0021_alter_zooniversesubject_bool_handwritten_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='bool_handwritten',
            field=models.BooleanField(null=True),
        ),
    ]
