# Generated by Django 4.0.3 on 2022-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0022_remove_zooniversesubject_deed_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='image_id_1',
        ),
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='image_id_2',
        ),
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='image_id_3',
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='image_ids',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
