# Generated by Django 4.0.3 on 2022-03-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0023_remove_zooniversesubject_image_id_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True, null=True)),
                ('zoon_workflow_id', models.IntegerField(db_index=True, null=True)),
                ('bool_covenant', models.BooleanField(null=True)),
                ('covenant_text', models.TextField(blank=True)),
                ('addition', models.CharField(blank=True, max_length=500)),
                ('lot', models.TextField(blank=True)),
                ('block', models.CharField(blank=True, max_length=500)),
                ('seller', models.CharField(blank=True, max_length=100)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.DateField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.zoon.zooniverseworkflow')),
                ('zooniverse_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.zoon.zooniversesubject')),
            ],
        ),
    ]
