# Generated by Django 4.1.2 on 2022-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0024_alter_zooniverseresponseprocessed_bool_handwritten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='match_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
