# Generated by Django 4.1.5 on 2023-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0026_zooniversesubject_match_type_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_s3_lookup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
