# Generated by Django 4.0.3 on 2022-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0026_zooniversesubject_bool_manual_correction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition_final',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Addition'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block_final',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='bool_manual_correction',
            field=models.BooleanField(default=False, verbose_name='Has manual updates'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer_final',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer name'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='covenant_text_final',
            field=models.TextField(blank=True, null=True, verbose_name='Covenant text'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='lot_final',
            field=models.TextField(blank=True, null=True, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller_final',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller name'),
        ),
    ]
