# Generated by Django 4.0.3 on 2022-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0027_alter_zooniversesubject_addition_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='bool_manual_correction',
            field=models.BooleanField(default=False, null=True, verbose_name='Has manual updates'),
        ),
    ]
