# Generated by Django 4.0.3 on 2022-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0028_alter_zooniversesubject_bool_manual_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='addition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='block',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='covenant_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='lot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
