# Generated by Django 4.1.5 on 2023-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0028_alter_zooniversesubject_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='buyer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='seller',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='buyer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='seller',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer name'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller name'),
        ),
    ]
