# Generated by Django 4.1.5 on 2023-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0029_alter_manualcorrection_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='match_type',
            field=models.CharField(blank=True, choices=[('SL', 'Simple lot'), ('ML', 'Multiple single lots'), ('MB', 'Lots spanning multiple blocks'), ('PL', 'Partial lot'), ('PD', 'Long phys description'), ('AW', 'Addition-wide covenant'), ('C', 'Cemetery plot'), ('PC', 'Petition covenant'), ('SE', 'Something else'), ('NG', 'No geographic information')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='match_type',
            field=models.CharField(blank=True, choices=[('SL', 'Simple lot'), ('ML', 'Multiple single lots'), ('MB', 'Lots spanning multiple blocks'), ('PL', 'Partial lot'), ('PD', 'Long phys description'), ('AW', 'Addition-wide covenant'), ('C', 'Cemetery plot'), ('PC', 'Petition covenant'), ('SE', 'Something else'), ('NG', 'No geographic information')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='match_type_final',
            field=models.CharField(blank=True, choices=[('SL', 'Simple lot'), ('ML', 'Multiple single lots'), ('MB', 'Lots spanning multiple blocks'), ('PL', 'Partial lot'), ('PD', 'Long phys description'), ('AW', 'Addition-wide covenant'), ('C', 'Cemetery plot'), ('PC', 'Petition covenant'), ('SE', 'Something else'), ('NG', 'No geographic information')], max_length=4, null=True, verbose_name='Match type'),
        ),
    ]
