# Generated by Django 4.1.5 on 2023-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0030_alter_manualcorrection_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition',
            field=models.CharField(blank=True, max_length=501),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block',
            field=models.CharField(blank=True, max_length=502),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=504),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=503),
        ),
    ]
