# Generated by Django 4.0.3 on 2022-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_parcel_orig_filename'),
        ('zoon', '0030_alter_manualcorrection_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='parcel_matches',
            field=models.ManyToManyField(to='apps.parcel.parcel'),
        ),
    ]
