# Generated by Django 4.1.5 on 2023-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0031_alter_zooniversesubject_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer_final',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Buyer name'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller_final',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Seller name'),
        ),
    ]
