# Generated by Django 4.0.3 on 2022-04-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0031_zooniversesubject_parcel_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_parcel_match',
            field=models.BooleanField(default=False),
        ),
    ]
