# Generated by Django 4.1.5 on 2023-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0032_alter_zooniversesubject_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition',
            field=models.CharField(blank=True, max_length=501),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block',
            field=models.CharField(blank=True, max_length=502),
        ),
    ]
