# Generated by Django 4.1.5 on 2023-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0033_alter_zooniversesubject_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='buyer',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='seller',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
