# Generated by Django 4.1.5 on 2023-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0034_alter_zooniverseresponseprocessed_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='city',
            field=models.CharField(blank=True, max_length=503),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='city_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='zoon_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
