# Generated by Django 4.1.5 on 2023-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0035_zooniverseresponseprocessed_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_doc_num',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_s3_lookup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
