# Generated by Django 4.1.5 on 2023-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0036_alter_zooniversesubject_deedpage_doc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition',
            field=models.CharField(blank=True, max_length=501, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block',
            field=models.CharField(blank=True, max_length=502, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='city',
            field=models.CharField(blank=True, max_length=503, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='lot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
