# Generated by Django 4.1.5 on 2023-07-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0038_alter_zooniverseresponseprocessed_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
