# Generated by Django 4.2.10 on 2024-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0042_zooniverseworkflow_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='buyer',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='seller',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
