# Generated by Django 4.2.10 on 2024-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0044_alter_zooniversesubject_buyer_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcovenant',
            name='block',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
