# Generated by Django 4.2.10 on 2024-04-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0045_alter_manualcovenant_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcovenant',
            name='lot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
