# Generated by Django 4.2.14 on 2024-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0046_alter_manualcovenant_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcovenant',
            name='parcel_addresses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualcovenant',
            name='parcel_city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
