# Generated by Django 4.2.15 on 2024-11-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0049_alter_zooniverseresponseprocessed_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualParcelPINLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('zoon_workflow_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parcel_pin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
                ('zooniverse_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject')),
            ],
        ),
    ]
