# Generated by Django 4.2.17 on 2025-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0051_manualcovenantparcelpinlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualcorrection',
            name='map_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manualcorrection',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manualcovenant',
            name='map_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manualcovenant',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='map_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book_final',
            field=models.CharField(blank=True, max_length=100, verbose_name='Map Book'),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book_page_final',
            field=models.CharField(blank=True, max_length=100, verbose_name='Map Book Page'),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book_page_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='map_book_score',
            field=models.FloatField(null=True),
        ),
    ]
