# Generated by Django 4.2.17 on 2025-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0052_manualcorrection_map_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_doc_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
