# Generated by Django 4.2.17 on 2025-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0054_alter_zooniverseresponseprocessed_map_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='map_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_final',
            field=models.CharField(blank=True, max_length=255, verbose_name='Map Book'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page_final',
            field=models.CharField(blank=True, max_length=255, verbose_name='Map Book Page'),
        ),
    ]
