# Generated by Django 5.2.2 on 2025-06-24 21:29

import apps.zoon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0055_alter_manualcorrection_map_book_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='image_ids',
        #     field=apps.zoon.models.CopyJSONField(blank=True),
        # ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='image_links',
        #     field=apps.zoon.models.CopyJSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='join_candidates',
        #     field=apps.zoon.models.CopyJSONField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Map Book'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Map Book Page'),
        ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='parcel_addresses',
        #     field=apps.zoon.models.CopyJSONField(blank=True, null=True),
        # ),
    ]
