# Generated by Django 5.2.2 on 2025-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0056_alter_zooniversesubject_image_ids_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='image_ids',
        #     field=models.JSONField(blank=True),
        # ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='image_links',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='join_candidates',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='zooniversesubject',
        #     name='parcel_addresses',
        #     field=models.JSONField(blank=True, null=True),
        # ),
    ]
