# Generated by Django 5.2.2 on 2025-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0057_alter_zooniversesubject_image_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseprocessed',
            name='zoon_subject_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
