# Generated by Django 5.2.2 on 2025-06-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0058_zooniverseresponseprocessed_zoon_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='map_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
