# Generated by Django 5.2.2 on 2025-08-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0059_alter_manualcorrection_map_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcovenant',
            name='doc_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manualcovenant',
            name='parcel_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualcovenantparcelpinlink',
            name='parcel_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualparcelpinlink',
            name='parcel_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reducedresponse_question',
            name='question_type',
            field=models.CharField(choices=[('q', 'question'), ('d', 'dropdown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='parcel_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseuser',
            name='zoon_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseuser',
            name='zoon_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='workflow_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='zoon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
