# Generated by Django 6.0.6 on 2026-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseworkflow',
            name='child_export_workflows',
            field=models.ManyToManyField(to='zoon.zooniverseworkflow'),
        ),
    ]
