# Generated by Django 6.0.6 on 2026-07-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0062_zooniverseworkflow_child_export_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book',
            field=models.CharField(blank=True, max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='street_address',
            field=models.CharField(blank=True, max_length=259, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book',
            field=models.CharField(blank=True, max_length=263, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_s3_lookup',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_final',
            field=models.CharField(blank=True, max_length=261, null=True, verbose_name='Map Book'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=259, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page_final',
            field=models.CharField(blank=True, max_length=262, null=True, verbose_name='Map Book Page'),
        ),
        migrations.AlterField(
            model_name='zooniverseworkflow',
            name='child_export_workflows',
            field=models.ManyToManyField(blank=True, to='zoon.zooniverseworkflow'),
        ),
    ]
