# Generated by Django 6.0.6 on 2026-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0063_alter_manualcorrection_map_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deedpage_s3_lookup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Map Book'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='map_book_page_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Map Book Page'),
        ),
    ]
