# Generated by Django 6.0.6 on 2026-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0066_alter_manualcorrection_map_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraparcelcandidate',
            name='addition',
            field=models.CharField(blank=True, max_length=514, null=True),
        ),
        migrations.AlterField(
            model_name='extraparcelcandidate',
            name='block',
            field=models.CharField(blank=True, max_length=515, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='addition',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='block',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='buyer',
            field=models.CharField(blank=True, max_length=513, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='seller',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='addition',
            field=models.CharField(blank=True, max_length=505, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='block',
            field=models.CharField(blank=True, max_length=506, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='city',
            field=models.CharField(blank=True, max_length=509, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book',
            field=models.CharField(blank=True, max_length=507, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='map_book_page',
            field=models.CharField(blank=True, max_length=508, null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition_final',
            field=models.CharField(blank=True, max_length=502, null=True, verbose_name='Addition'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block_final',
            field=models.CharField(blank=True, max_length=503, null=True, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='city_final',
            field=models.CharField(blank=True, max_length=504, null=True, verbose_name='City'),
        ),
    ]
