# Generated by Django 6.0 on 2026-09-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0067_alter_extraparcelcandidate_addition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='geom_union_4326',
        ),
    ]
