# Generated by Django 4.0.4 on 2022-04-14 16:23

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(blank=True, max_length=100)),
                ('page_num', models.IntegerField(null=True)),
                ('doc_date', models.DateField(null=True)),
                ('page_image_web', models.ImageField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('page_ocr_text', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('bool_match', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True)),
                ('bool_covenant', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('workflow_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseResponseRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('workflow_id', models.IntegerField(null=True)),
                ('workflow_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('workflow_version', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('gold_standard', models.BooleanField(null=True)),
                ('expert', models.BooleanField(null=True)),
                ('metadata', models.JSONField()),
                ('annotations', models.JSONField()),
                ('subject_data', models.JSONField()),
                ('subject_ids', models.IntegerField(db_index=True)),
                ('subject_data_flat', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('zoon_name', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohen_kappa', models.FloatField(null=True)),
                ('n_clfs', models.IntegerField(null=True)),
                ('reliability_score', models.FloatField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.zooniverseuser')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseResponseFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('bool_covenant', models.BooleanField(null=True)),
                ('bool_outlier', models.BooleanField(default=False)),
                ('covenant_text', models.TextField(blank=True)),
                ('addition', models.CharField(blank=True, max_length=500)),
                ('lot', models.TextField(blank=True)),
                ('block', models.CharField(blank=True, max_length=500)),
                ('seller', models.CharField(blank=True, max_length=100)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.DateField(null=True)),
                ('dt_created', models.DateTimeField()),
                ('dt_retired', models.DateTimeField(null=True)),
                ('raw_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deed.zooniverseresponseraw')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.potentialmatch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.zooniverseuser')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='potentialmatch',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.workflow'),
        ),
    ]
