# Generated by Django 4.0.4 on 2022-04-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoon', '0001_initial'),
        ('deed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow'),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='zooniverse_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject'),
        ),
    ]
