# Generated by Django 4.0.5 on 2022-07-14 14:25

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0013_extraparcelcandidate_epc_type'),
        ('deed', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_csv', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('num_hits', models.IntegerField(null=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow')),
            ],
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseflat',
            name='raw_match',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseflat',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseflat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseflat',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='zooniverseuserrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zooniverseuserrating',
            name='workflow',
        ),
        migrations.AddField(
            model_name='deedpage',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='matched_terms',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='PotentialMatch',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='ZooniverseResponseFlat',
        ),
        migrations.DeleteModel(
            name='ZooniverseResponseRaw',
        ),
        migrations.DeleteModel(
            name='ZooniverseUser',
        ),
        migrations.DeleteModel(
            name='ZooniverseUserRating',
        ),
    ]
