# Generated by Django 4.0.5 on 2022-07-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0005_deedpage_s3_lookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='deedpage',
            name='matched_terms',
        ),
        migrations.AddField(
            model_name='deedpage',
            name='matched_terms',
            field=models.ManyToManyField(to='deed.matchterm'),
        ),
    ]
