# Generated by Django 4.0.5 on 2022-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0007_deedpage_page_ocr_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='doc_alt_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
