# Generated by Django 4.0.6 on 2022-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0010_deedpage_page_stats_deedpage_public_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='bool_exception',
            field=models.BooleanField(default=False),
        ),
    ]
