# Generated by Django 4.1 on 2022-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0011_deedpage_bool_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
