# Generated by Django 4.1 on 2022-08-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0012_alter_deedpage_doc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='bool_exception',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='bool_match',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
