# Generated by Django 4.1.1 on 2022-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0013_alter_deedpage_bool_exception_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow', 'id'], name='workflow_id_index'),
        ),
    ]
