# Generated by Django 4.1.1 on 2022-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0014_deedpage_workflow_id_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deedpage',
            name='workflow_id_index',
        ),
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id', 'id'], name='workflow_id_index'),
        ),
    ]
