# Generated by Django 4.1.1 on 2022-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0015_remove_deedpage_workflow_id_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id'], name='workflow_only_index'),
        ),
    ]
