# Generated by Django 4.1.1 on 2022-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0016_deedpage_workflow_only_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deedpage',
            name='workflow_id_index',
        ),
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['-id'], name='id_desc'),
        ),
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id', '-id'], name='workflow_id_index'),
        ),
    ]
