# Generated by Django 4.1.1 on 2022-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0017_remove_deedpage_workflow_id_index_deedpage_id_desc_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['-id', 'workflow_id'], name='id_workflow_index'),
        ),
    ]
