# Generated by Django 4.1.2 on 2023-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0019_deedpage_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='book_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
