# Generated by Django 4.1.2 on 2023-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0020_deedpage_batch_id_alter_deedpage_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
