# Generated by Django 4.1.5 on 2023-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0022_alter_deedpage_page_image_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='split_page_num',
            field=models.IntegerField(null=True),
        ),
    ]
