# Generated by Django 4.1.5 on 2023-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0023_deedpage_split_page_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='doc_page_count',
            field=models.IntegerField(null=True),
        ),
    ]
