# Generated by Django 4.1.5 on 2023-07-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0026_deedpage_prev_deedpage_2'),
    ]

    operations = [
    ]
