# Generated by Django 4.1.5 on 2023-07-07 23:16

from django.db import migrations, models
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0027_alter_deedpage_next_deedpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deedpage',
            name='next_deedpage',
        ),
        migrations.RemoveField(
            model_name='deedpage',
            name='next_next_deedpage',
        ),
        migrations.RemoveField(
            model_name='deedpage',
            name='prev_deedpage',
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='next_next_page_image_web',
            field=models.ImageField(db_index=True, max_length=200, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='next_page_image_web',
            field=models.ImageField(db_index=True, max_length=200, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='prev_page_image_web',
            field=models.ImageField(db_index=True, max_length=200, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
    ]
