# Generated by Django 4.1.5 on 2023-07-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0028_remove_deedpage_prev_deedpage_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='next_deedpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_deedpage_set', to='deed.deedpage'),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='next_next_deedpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_next_deedpage_set', to='deed.deedpage'),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='prev_deedpage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prev_deedpage_set', to='deed.deedpage'),
        ),
    ]
