# Generated by Django 4.1.5 on 2023-07-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0029_deedpage_next_deedpage_deedpage_next_next_deedpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deedpage',
            name='next_deedpage',
        ),
        migrations.RemoveField(
            model_name='deedpage',
            name='next_next_deedpage',
        ),
        migrations.RemoveField(
            model_name='deedpage',
            name='prev_deedpage',
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='page_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='split_page_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
