# Generated by Django 4.2.5 on 2023-09-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0040_zooniversesubject_image_links'),
        ('deed', '0031_deedpage_next_next_page_image_lookup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='zooniverse_subject_1st_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_1st_page', to='zoon.zooniversesubject'),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='zooniverse_subject_2nd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_2nd_page', to='zoon.zooniversesubject'),
        ),
        migrations.AddField(
            model_name='deedpage',
            name='zooniverse_subject_3rd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_3rd_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_legacy', to='zoon.zooniversesubject'),
        ),
    ]
