# Generated by Django 4.2.5 on 2024-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0032_deedpage_zooniverse_subject_1st_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='bool_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
