# Generated by Django 4.2.10 on 2024-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0034_alter_deedpage_book_id_alter_deedpage_doc_alt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=204),
        ),
    ]
