# Generated by Django 4.2.14 on 2024-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0037_alter_deedpage_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhitreport',
            name='num_exceptions',
            field=models.IntegerField(null=True),
        ),
    ]
