# Generated by Django 4.2.15 on 2024-11-01 18:25

from django.db import migrations, models
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0038_searchhitreport_num_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='page_image_web_highlighted',
            field=models.ImageField(db_index=True, max_length=201, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
    ]
