# Generated by Django 4.2.17 on 2025-04-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0039_deedpage_page_image_web_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='book_id',
            field=models.CharField(blank=True, db_index=True, max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='doc_type',
            field=models.CharField(blank=True, max_length=104, null=True),
        ),
    ]
