# Generated by Django 4.2.17 on 2025-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0040_alter_deedpage_batch_id_alter_deedpage_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=101, null=True),
        ),
    ]
