# Generated by Django 5.2.2 on 2025-08-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0041_alter_deedpage_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_alt_id',
            field=models.CharField(blank=True, max_length=102),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='public_uuid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
