# Generated by Django 5.2.2 on 2025-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0042_alter_deedpage_doc_alt_id_alter_deedpage_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
