# Generated by Django 5.2.2 on 2025-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0043_alter_deedpage_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=101, null=True),
        ),
    ]
