# Generated by Django 5.2.2 on 2025-08-27 17:22

import racial_covenants_processor.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0045_alter_deedpage_book_id_alter_deedpage_bool_exception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='book_id',
            field=models.CharField(blank=True, db_index=True, max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='bool_exception',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='bool_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='bool_match',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='doc_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='next_next_page_image_web',
            field=models.ImageField(db_index=True, max_length=203, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='next_page_image_web',
            field=models.ImageField(db_index=True, max_length=202, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='page_image_web_highlighted',
            field=models.ImageField(db_index=True, max_length=201, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='page_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='prev_page_image_web',
            field=models.ImageField(db_index=True, max_length=201, null=True, storage=racial_covenants_processor.storage_backends.PublicDeedStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='s3_lookup',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='split_page_num',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchterm',
            name='term',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
