# Generated by Django 5.2.2 on 2025-08-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0046_alter_deedpage_book_id_alter_deedpage_bool_exception_and_more'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_1st_page',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_1st_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_2nd_page',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_2nd_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_3rd_page',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_3rd_page', to='zoon.zooniversesubject'),
        ),
    ]
