# Generated by Django 5.2.2 on 2025-08-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0047_alter_deedpage_zooniverse_subject_1st_page_and_more'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_1st_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_1st_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_2nd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_2nd_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_3rd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_3rd_page', to='zoon.zooniversesubject'),
        ),
    ]
