# Generated by Django 5.2.7 on 2025-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0048_alter_deedpage_zooniverse_subject_1st_page_and_more'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['zooniverse_subject_1st_page_id'], name='zpage_1_index'),
        ),
    ]
