# Generated by Django 5.2.7 on 2025-11-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0049_deedpage_zpage_1_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deedpage',
            name='zpage_1_index',
        ),
    ]
