# Generated by Django 5.2.7 on 2025-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0050_remove_deedpage_zpage_1_index'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['zooniverse_subject_1st_page_id'], name='zpage_1_index'),
        ),
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['zooniverse_subject_2nd_page_id'], name='zpage_2_index'),
        ),
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['zooniverse_subject_3rd_page_id'], name='zpage_3_index'),
        ),
    ]
