# Generated by Django 5.2.7 on 2025-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0051_deedpage_zpage_1_index_deedpage_zpage_2_index_and_more'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id', 'bool_match'], name='workflow_plus_match_index'),
        ),
    ]
