# Generated by Django 5.2.7 on 2025-11-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0052_deedpage_workflow_plus_match_index'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id', 's3_lookup'], name='s3_lookup_workflow_index'),
        ),
    ]
