# Generated by Django 5.2.7 on 2025-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0053_deedpage_s3_lookup_workflow_index'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedpage',
            index=models.Index(fields=['workflow_id', 'batch_id', 'book_id', 'doc_num', 'doc_type', 'page_num'], name='workflow_pagination_index'),
        ),
    ]
