# Generated by Django 5.2.7 on 2025-12-01 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0054_deedpage_workflow_pagination_index'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_legacy', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_1st_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_1st_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_2nd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_2nd_page', to='zoon.zooniversesubject'),
        ),
        migrations.AlterField(
            model_name='deedpage',
            name='zooniverse_subject_3rd_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_3rd_page', to='zoon.zooniversesubject'),
        ),
    ]
