# Generated by Django 5.2.7 on 2025-12-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0055_alter_deedpage_zooniverse_subject_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deedpage',
            name='zpage_1_index',
        ),
        migrations.RemoveIndex(
            model_name='deedpage',
            name='zpage_2_index',
        ),
        migrations.RemoveIndex(
            model_name='deedpage',
            name='zpage_3_index',
        ),
    ]
