# Generated by Django 4.0.3 on 2022-04-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='geom',
            new_name='geom_4326',
        ),
    ]
