# Generated by Django 4.0.3 on 2022-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_alter_parcel_block_alter_parcel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='orig_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
