# Generated by Django 4.0.1 on 2022-01-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZooniverseResponseRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_id', models.IntegerField()),
                ('workflow_id', models.CharField(blank=True, max_length=100)),
                ('workflow_name', models.CharField(blank=True, max_length=10)),
                ('workflow_version', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, max_length=10)),
                ('gold_standard', models.BooleanField(null=True)),
                ('expert', models.BooleanField(null=True)),
                ('metadata', models.JSONField()),
                ('annotations', models.JSONField()),
                ('subject_data', models.JSONField()),
                ('subject_ids', models.IntegerField()),
            ],
        ),
    ]
