# Generated by Django 4.0.1 on 2022-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0002_alter_zooniverseresponseraw_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='workflow_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
