# Generated by Django 4.0.1 on 2022-01-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0003_alter_zooniverseresponseraw_workflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='subject_ids',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='user_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='workflow_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
