# Generated by Django 4.0.1 on 2022-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0004_alter_zooniverseresponseraw_subject_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='subject_data_flat',
            field=models.JSONField(null=True),
        ),
    ]
