# Generated by Django 4.0.1 on 2022-01-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0005_zooniverseresponseraw_subject_data_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True)),
                ('bool_covenant', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('workflow_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_id', models.IntegerField(db_index=True, null=True)),
                ('zoon_name', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ZooniverseResponseFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('bool_covenant', models.BooleanField()),
                ('covenant_text', models.TextField(blank=True)),
                ('addition', models.CharField(blank=True, max_length=100)),
                ('lot', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('seller', models.CharField(blank=True, max_length=100)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.CharField(blank=True, max_length=100)),
                ('dt_created', models.DateTimeField()),
                ('dt_retired', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deeds.potentialmatch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deeds.zooniverseuser')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deeds.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='potentialmatch',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deeds.workflow'),
        ),
    ]
