# Generated by Django 4.0.1 on 2022-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0007_zooniverseresponseflat_bool_outlier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='bool_covenant',
            field=models.BooleanField(null=True),
        ),
    ]
