# Generated by Django 4.0.1 on 2022-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0008_alter_zooniverseresponseflat_bool_covenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='deed_date',
            field=models.DateField(null=True),
        ),
    ]
