# Generated by Django 4.0.1 on 2022-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0009_alter_zooniverseresponseflat_deed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='dt_retired',
            field=models.DateTimeField(null=True),
        ),
    ]
