# Generated by Django 4.0.1 on 2022-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0013_alter_zooniverseresponseflat_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='addition',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
