# Generated by Django 4.0.3 on 2022-03-28 15:50

from django.db import migrations, models
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0017_zooniverseuserrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(blank=True, max_length=100)),
                ('page_num', models.IntegerField(null=True)),
                ('doc_date', models.DateField(null=True)),
                ('page_image_web', models.ImageField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('page_ocr_text', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('bool_match', models.BooleanField(default=False)),
            ],
        ),
    ]
