# Generated by Django 4.0.3 on 2022-03-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0019_zooniversesubject_median_score'),
        ('deeds', '0018_deedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow'),
        ),
    ]
