# Generated by Django 4.0.3 on 2022-03-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0022_remove_zooniversesubject_deed_images'),
        ('deeds', '0019_deedpage_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpage',
            name='zooniverse_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject'),
        ),
    ]
