# Generated by Django 4.0.1 on 2022-01-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReducedResponse_Question',
        ),
        migrations.DeleteModel(
            name='ReducedResponse_Text',
        ),
    ]
