# Generated by Django 4.0.1 on 2022-01-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoon', '0002_delete_reducedresponse_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedResponse_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True)),
                ('zoon_workflow_id', models.IntegerField(db_index=True)),
                ('task_id', models.CharField(db_index=True, max_length=4)),
                ('best_answer', models.TextField()),
                ('best_answer_score', models.FloatField()),
                ('total_votes', models.IntegerField()),
                ('answer_scores', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReducedResponse_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(db_index=True)),
                ('zoon_workflow_id', models.IntegerField(db_index=True)),
                ('task_id', models.CharField(db_index=True, max_length=4)),
                ('aligned_text', models.JSONField()),
                ('total_votes', models.IntegerField()),
                ('consensus_score', models.IntegerField()),
                ('user_ids', models.JSONField()),
            ],
        ),
    ]
