# Generated by Django 4.0.1 on 2022-01-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducedresponse_text',
            name='consensus_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
