# Generated by Django 4.0.1 on 2022-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0004_reducedresponse_text_consensus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducedresponse_question',
            name='question_type',
            field=models.CharField(choices=[('q', 'question'), ('d', 'dropdown')], db_index=True, default='q', max_length=1),
            preserve_default=False,
        ),
    ]
