# Generated by Django 4.0.1 on 2022-01-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0006_zooniverseresponseraw_zooniverseuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='addition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='block',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_outlier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='covenant_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='dt_retired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='lot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='seller',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
