# Generated by Django 4.0.1 on 2022-02-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0008_remove_zooniversesubject_bool_outlier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_problem',
            field=models.BooleanField(default=False),
        ),
    ]
