# Generated by Django 4.0.3 on 2022-03-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0010_zooniversesubject_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject'),
        ),
    ]
