# Generated by Django 4.0.3 on 2022-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0011_zooniverseresponseraw_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='covenant_text',
            field=models.TextField(blank=True),
        ),
    ]
