# Generated by Django 4.0.3 on 2022-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0012_zooniverseresponseraw_covenant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='covenant_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
