# Generated by Django 4.0.3 on 2022-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0013_alter_zooniverseresponseraw_covenant_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='addition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='block',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='bool_covenant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='deed_date_day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='deed_date_month',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='deed_date_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='lot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zooniverseresponseraw',
            name='seller',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zooniverseresponseraw',
            name='covenant_text',
            field=models.TextField(blank=True),
        ),
    ]
