# Generated by Django 4.0.3 on 2022-03-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0014_zooniverseresponseraw_addition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='block',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='bool_covenant',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='covenant_text',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='deed_date_day',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='deed_date_month',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='deed_date_year',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='zooniverseresponseraw',
            name='seller',
        ),
        migrations.CreateModel(
            name='ZooniverseResponseProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('bool_covenant', models.CharField(blank=True, max_length=100)),
                ('covenant_text', models.TextField(blank=True)),
                ('addition', models.CharField(blank=True, max_length=500)),
                ('lot', models.TextField(blank=True)),
                ('block', models.CharField(blank=True, max_length=500)),
                ('seller', models.CharField(blank=True, max_length=100)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('deed_date_year', models.CharField(blank=True, max_length=10)),
                ('deed_date_month', models.CharField(blank=True, max_length=100)),
                ('deed_date_day', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField()),
                ('response_raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseresponseraw')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
