# Generated by Django 4.0.3 on 2022-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0015_remove_zooniverseresponseraw_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseprocessed',
            name='bool_covenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
