# Generated by Django 4.0.3 on 2022-03-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0018_zooniverseworkflow_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='median_score',
            field=models.FloatField(null=True),
        ),
    ]
