# Generated by Django 4.0.3 on 2022-03-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0019_deedpage_workflow'),
        ('zoon', '0020_remove_zooniversesubject_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_images',
            field=models.ManyToManyField(to='deeds.deedpage'),
        ),
    ]
