# Generated by Django 4.0.3 on 2022-03-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0021_zooniversesubject_deed_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversesubject',
            name='deed_images',
        ),
    ]
