# Generated by Django 4.0.3 on 2022-03-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0024_manualcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='addition_final',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='block_final',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_covenant_final',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='buyer_final',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='covenant_text_final',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='deed_date_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='lot_final',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='seller_final',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='deed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='zoon_subject_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualcorrection',
            name='zoon_workflow_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
