# Generated by Django 4.0.3 on 2022-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0025_zooniversesubject_addition_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='bool_manual_correction',
            field=models.BooleanField(default=False, verbose_name='Record has manual updates'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='addition_final',
            field=models.CharField(blank=True, max_length=500, verbose_name='Addition'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='block_final',
            field=models.CharField(blank=True, max_length=500, verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='bool_covenant_final',
            field=models.BooleanField(null=True, verbose_name='Has racial covenant'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='buyer_final',
            field=models.CharField(blank=True, max_length=100, verbose_name='Buyer name'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='covenant_text_final',
            field=models.TextField(blank=True, verbose_name='Covenant text'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='deed_date_final',
            field=models.DateField(blank=True, null=True, verbose_name='Deed date'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='lot_final',
            field=models.TextField(blank=True, verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='seller_final',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seller name'),
        ),
    ]
