# Generated by Django 4.0.3 on 2022-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0029_alter_manualcorrection_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcorrection',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
