# Generated by Django 4.0.3 on 2022-04-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0032_zooniversesubject_bool_parcel_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraParcelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_subject_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('zoon_workflow_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('addition', models.CharField(blank=True, max_length=500, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
                ('zooniverse_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniversesubject')),
            ],
        ),
    ]
