# Generated by Django 4.0.3 on 2022-04-11 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0033_extraparcelcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversesubject',
            name='geom_union_4326',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
