# Generated by Django 4.0.4 on 2022-04-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0002_alter_plat_options_alter_platalternatename_plat_name'),
        ('parcel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plat.plat'),
        ),
    ]
