# Generated by Django 4.0.3 on 2022-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_rename_geom_parcel_geom_4326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='join_description',
            field=models.TextField(blank=True),
        ),
    ]
