# Generated by Django 4.0.4 on 2022-04-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0002_zooniversesubject_date_updated'),
        ('parcel', '0004_parcel_plat_standardized'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelJoinCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name_standardized', models.CharField(db_index=True, max_length=255, null=True)),
                ('join_string', models.CharField(db_index=True, max_length=255, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcel')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
