# Generated by Django 4.0.4 on 2022-05-13 14:31

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0011_zooniversesubject_match_type_and_more'),
        ('parcel', '0006_parceljoincandidate_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_csv', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='analysis/')),
                ('covenant_count', models.IntegerField()),
                ('matched_lot_count', models.IntegerField()),
                ('matched_subject_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
