# Generated by Django 4.1.5 on 2023-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0010_geojsonexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='lot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
