# Generated by Django 4.1.5 on 2023-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0011_alter_parcel_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
