# Generated by Django 4.1.5 on 2023-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0013_alter_parcel_city_alter_parcel_plat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceljoincandidate',
            name='join_string',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
