# Generated by Django 4.1.5 on 2023-02-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0005_subdivision'),
        ('parcel', '0014_alter_parceljoincandidate_join_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plat.subdivision'),
        ),
    ]
