# Generated by Django 4.1.5 on 2023-02-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0015_parcel_subdivision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='subdivision',
            new_name='subdivision_spatial',
        ),
    ]
