# Generated by Django 4.1.5 on 2023-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0017_alter_csvexport_options_alter_geojsonexport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='bool_covenant',
            field=models.BooleanField(default=False),
        ),
    ]
