# Generated by Django 4.1.5 on 2023-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0018_parcel_bool_covenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='bool_covenant',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
