# Generated by Django 4.2.5 on 2023-10-19 18:19

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0040_zooniversesubject_image_links'),
        ('parcel', '0019_alter_parcel_bool_covenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCSVExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='main_exports/')),
                ('covenant_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UnmappedCSVExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='main_exports/')),
                ('covenant_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
