# Generated by Django 4.2.10 on 2024-02-29 17:34

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0041_alter_zooniverseresponseprocessed_subject'),
        ('parcel', '0020_validationcsvexport_unmappedcsvexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCovenantedDocsCSVExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='main_exports/')),
                ('docs_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
