# Generated by Django 4.2.10 on 2024-02-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0021_allcovenanteddocscsvexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcovenanteddocscsvexport',
            old_name='docs_count',
            new_name='doc_count',
        ),
    ]
