# Generated by Django 4.2.14 on 2024-07-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0023_alter_parcel_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinreport',
            old_name='covenant_count',
            new_name='covenanted_doc_count',
        ),
    ]
