# Generated by Django 4.2.14 on 2024-07-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0047_manualcovenant_parcel_addresses_and_more'),
        ('parcel', '0024_rename_covenant_count_joinreport_covenanted_doc_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualParcelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_pin_primary', models.IntegerField(blank=True, db_index=True, null=True)),
                ('addition', models.CharField(blank=True, max_length=500, null=True)),
                ('lot', models.TextField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.parcel')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
