# Generated by Django 4.2.14 on 2024-07-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0025_manualparcelcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualparcelcandidate',
            name='parcel_pin_primary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
