# Generated by Django 4.2.14 on 2024-07-19 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0047_manualcovenant_parcel_addresses_and_more'),
        ('parcel', '0026_alter_manualparcelcandidate_parcel_pin_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualparcelcandidate',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.parcel'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow'),
        ),
    ]
