# Generated by Django 4.2.14 on 2024-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0027_alter_manualparcelcandidate_parcel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualparcelcandidate',
            name='workflow_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
