# Generated by Django 4.2.15 on 2024-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0028_manualparcelcandidate_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='pin_primary',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
