# Generated by Django 5.2.2 on 2025-08-29 21:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0049_alter_parcel_state'),
        ('zoon', '0061_alter_manualcovenant_doc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='state',
            field=models.CharField(blank=True, choices="(('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))", db_index=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CovenantedParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnty_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('cnty_fips', models.CharField(max_length=255, null=True)),
                ('doc_num', models.CharField(max_length=255, null=True)),
                ('deed_year', models.IntegerField(null=True)),
                ('deed_date', models.DateField(null=True)),
                ('cov_text', models.TextField(null=True)),
                ('seller', models.CharField(max_length=1200, null=True)),
                ('buyer', models.CharField(max_length=1200, null=True)),
                ('street_add', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(db_index=True, max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('add_cov', models.CharField(max_length=500, null=True)),
                ('block_cov', models.CharField(max_length=100, null=True)),
                ('lot_cov', models.CharField(max_length=500, null=True)),
                ('map_book', models.CharField(max_length=255, null=True)),
                ('map_page', models.CharField(max_length=255, null=True)),
                ('cnty_pin', models.CharField(max_length=50, null=True)),
                ('add_mod', models.CharField(max_length=500, null=True)),
                ('block_mod', models.CharField(max_length=100, null=True)),
                ('lot_mod', models.CharField(max_length=500, null=True)),
                ('ph_dsc_mod', models.TextField(null=True)),
                ('join_strgs', models.JSONField(null=True)),
                ('cov_type', models.CharField(max_length=25, null=True)),
                ('match_type', models.CharField(max_length=255, null=True)),
                ('manual_cx', models.BooleanField(null=True)),
                ('dt_updated', models.DateField(null=True)),
                ('zn_subj_id', models.IntegerField(null=True)),
                ('zn_dt_ret', models.DateField(null=True)),
                ('image_ids', models.JSONField(null=True)),
                ('med_score', models.FloatField(null=True)),
                ('plat_dbid', models.IntegerField(null=True)),
                ('subd_dbid', models.IntegerField(null=True)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.parcel')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
