# Generated by Django 6.0.5 on 2026-08-28 12:12

import django.db.models.deletion
import racial_covenants_processor.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0072_parcelpmtilesexport'),
        ('zoon', '0062_zooniverseworkflow_child_export_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_file', models.FileField(null=True, storage=racial_covenants_processor.storage_backends.PublicMediaStorage(), upload_to='main_exports/')),
                ('parcel_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
