# Generated by Django 6.0.5 on 2026-08-28 13:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0073_parcelsearchindex'),
        ('zoon', '0062_zooniverseworkflow_child_export_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovenantDrawnGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('comments', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('manual_covenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.manualcovenant')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
                ('zooniverse_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoon.zooniversesubject')),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['workflow', 'zooniverse_subject'], name='parcel_cove_workflo_455e22_idx'), models.Index(fields=['workflow', 'manual_covenant'], name='parcel_cove_workflo_bd9a0e_idx')],
            },
        ),
    ]
