# Generated by Django 6.0.5 on 2026-08-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0074_covenantdrawngeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='covenantedparcel',
            name='drawn_geometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcel.covenantdrawngeometry'),
        ),
    ]
