# Generated by Django 4.0.1 on 2022-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0006_potentialmatch_workflow_zooniverseuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniverseresponseflat',
            name='bool_outlier',
            field=models.BooleanField(default=False),
        ),
    ]
