# Generated by Django 4.0.1 on 2022-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0010_alter_zooniverseresponseflat_dt_retired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='addition',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
