# Generated by Django 4.0.1 on 2022-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0011_alter_zooniverseresponseflat_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='lot',
            field=models.TextField(blank=True),
        ),
    ]
