# Generated by Django 4.0.1 on 2022-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0012_alter_zooniverseresponseflat_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='block',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
