# Generated by Django 4.0.1 on 2022-01-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0015_zooniverseresponseflat_raw_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseresponseflat',
            name='raw_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.deeds.zooniverseresponseraw'),
        ),
    ]
