# Generated by Django 4.0.4 on 2022-04-15 16:32

from django.db import migrations, models
import django.db.models.deletion
import racial_covenants_processor.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zoon', '0002_zooniversesubject_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('plat_year', models.IntegerField(blank=True, null=True)),
                ('book_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gov_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='PlatMapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(null=True)),
                ('remote_link', models.URLField(blank=True)),
                ('page_image_web', models.ImageField(null=True, storage=racial_covenants_processor.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plat.plat')),
            ],
        ),
        migrations.CreateModel(
            name='PlatAlternateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('alternate_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('plat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plat.plat')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
