# Generated by Django 4.0.4 on 2022-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['plat_name']},
        ),
        migrations.AlterField(
            model_name='platalternatename',
            name='plat_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
