# Generated by Django 4.0.4 on 2022-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0002_alter_plat_options_alter_platalternatename_plat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='plat_name_standardized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platalternatename',
            name='alternate_name_standardized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
