# Generated by Django 4.0.4 on 2022-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0003_plat_plat_name_standardized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platalternatename',
            name='zoon_workflow_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
