# Generated by Django 4.1.5 on 2023-02-22 22:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0030_alter_manualcorrection_match_type_and_more'),
        ('plat', '0004_platalternatename_zoon_workflow_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name_standardized', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('doc_num', models.CharField(blank=True, db_index=True, max_length=100)),
                ('recorded_date', models.DateField(db_index=True, null=True)),
                ('orig_data', models.JSONField(blank=True, null=True)),
                ('orig_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('geom_4326', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
