# Generated by Django 4.1.5 on 2023-02-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoon', '0030_alter_manualcorrection_match_type_and_more'),
        ('plat', '0005_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionAlternateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_workflow_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('subdivision_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('alternate_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('alternate_name_standardized', models.CharField(db_index=True, max_length=255, null=True)),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plat.subdivision')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoon.zooniverseworkflow')),
            ],
        ),
    ]
