# Generated by Django 5.2.2 on 2025-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0008_alter_plat_book_name_alter_plat_plat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='book_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='plat_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='plat_name_standardized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platalternatename',
            name='alternate_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platalternatename',
            name='alternate_name_standardized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platalternatename',
            name='plat_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='doc_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name_standardized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='recorded_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdivisionalternatename',
            name='alternate_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivisionalternatename',
            name='alternate_name_standardized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subdivisionalternatename',
            name='subdivision_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
