name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install gdal and postgis
      run: |
        sudo apt-add-repository ppa:ubuntugis
        sudo apt update
        sudo apt install gdal-bin libgdal-dev
        sudo apt install postgresql-10-postgis-scripts
    - name: Install Dependencies with pipenv
      run: |
        pip install pipenv
        pipenv install
    - name: Run Tests
      run: |
        pipenv run python manage.py test apps.plat
